### ISSUE TITLE
Use QUnit NPM or Bower release

### ISSUE THREAD

**Issue by daffl** [stealjs/steal-qunit#1]
Now that [this issue](https://github.com/jquery/qunit/issues/723) is closed and fixed in version [1.17.0](https://github.com/jquery/qunit/releases/tag/1.17.0) we should use the actual QUnit module release.

**Comment by matthewp** [comment]
I'd like to fix this @daffl can we talk about it today?

**Comment by justinbmeyer** [comment]
Quint will still need to be copied for npm installs. The npm quint does not work in the client.

**Comment by matthewp** [comment]
@justinbmeyer I see 2 qunits in npm, one is `qunit` which appears to be a node thing and `qunitjs` which is the "real" QUnit. It's main points to the same thing we have here.

**Comment by justinbmeyer** [comment]
oh, cool.
