### ISSUE TITLE
Add support for QUnit 2

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal-qunit#31]
This is a follow up to https://github.com/stealjs/steal-qunit/issues/5

Right now the [major branch](https://github.com/stealjs/steal-qunit/tree/major) has the 1.1.0-beta.1 release of steal-qunit with QUnit 2 support. We should make an official release that supports QUnit 2. 

I think this should be a breaking change with a new major version number. QUnit changed their npm package name from `qunitjs` to `qunit`, so I’m not sure if we can / want to support both versions in one major version of steal-qunit.

With the assumption that we want to make a new major version, here’s what I think needs to happen:

- [x] Update `major` with what’s in `master`
- [x] Change `major` to use the `qunit` package instead of `qunitjs` (and also remove compatibility with QUnit 2)
- [x] Fix issues
- [x] Drop Bower?
- [x] Drop Grunt?
- [x] Upgrade any other dependencies & make sure the build is working
- [x] Release

**Comment by chasenlehara** [comment]
I’ve started a branch/PR with these changes. @cherifGsoul, mind picking it up from here please? https://github.com/stealjs/steal-qunit/pull/32

**Comment by cherifGsoul** [comment]
Funcunit is not loading qunit tests in iframes, which causes an error, the message in this [line](https://github.com/bitovi/funcunit/blob/b6eddccaf66c31fdf2ac27dc976a587a723f1c22/browser/adapters/qunit2.js#L21):
 
`beforeEach failed on Banner shows as passing: currentTestAssert is undefined`

I guess is there’s a timeout issue in qunit2 adapter for funcunit

**Comment by cherifGsoul** [comment]
QUnit 2 was released.
https://github.com/stealjs/steal-qunit/releases/tag/v2.0.0
