### ISSUE TITLE
Adding funcunit tests back

### ISSUE THREAD

**Issue by cherifGsoul** [stealjs/steal-qunit#33]
To make `v2.0.0` release `funcunit` was not working with `QUnit2`so the tests with `funcunit` was dropped until the issue will be fixed.

**Comment by chasenlehara** [comment]
@kdillon Have you been working on QUnit 2 support in FuncUnit?

**Comment by cherifGsoul** [comment]
Not yet, I'll do today.

**Comment by cherifGsoul** [comment]
https://github.com/bitovi/funcunit/issues/234

**Comment by kdillon** [comment]
Hi @chasenlehara , @cherifGsoul . Yes the QUnit 2 stuff is in for FuncUnit. Its waiting on review.

https://github.com/bitovi/funcunit/pull/240

I would just push it, but as you know Chasen, my local funcunit project is currently borked for some reason, and so I can't independently verify that the change merged elegantly. However it does appear to have passed in Travis.
