### ISSUE TITLE
QUnit 2

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-qunit#5]
Current steal-qunit works with only QUnit 1.x.  Eventually people will want QUnit 2 as well.  My thought was that we could tag the current steal-qunit as 1.0 and then create a 2.0 which is compatible with QUnit 2.0. This way people who want the older QUnit can still get it with steal-qunit 1.x.  Since new features are infrequent it won't be much trouble to maintain the 2 separate versions.

**Comment by leoj3n** [comment]
http://qunitjs.com/upgrade-guide-2.x/

> Note that all the new APIs of QUnit 2.0 are already usable in QUnit 1.21.0, allowing you to migrate step by step. QUnit 2.0 will include a migration layer that throws descriptive errors for all deprecated methods 

Doesn't this mean you don't really need to manage two versions? People could just check out older releases with package.json that includes older qunit like https://github.com/stealjs/steal-qunit/blob/cf890a7887cafda7d76c119236aa386b449de7ab/package.json#L59

**Comment by Qazzian** [comment]
Since your last comment the Situation has changed slightly:

> Note that almost all the new APIs of QUnit 2.0.0 are already usable in QUnit 1.23.1, allowing you to migrate step by step. **The only exception is the new module hooks _before_ and _after_.**

**Comment by matthewp** [comment]
@pYr0x you expressed interest in doing this.  Do you think it would be possible to make it compatible with both 1.x and 2.x? That is, if a user is using 1.x it still works, or if they are using 2.x it works as well? That would be most ideal, as it would mean we wouldn't have to release steal-qunit 2.x

**Comment by matthewp** [comment]
Fixed by https://github.com/stealjs/steal-qunit/pull/27
