### ISSUE TITLE
Module evaluation errors cause 0 tests to run successfully

### ISSUE THREAD

**Issue by daffl** [stealjs/steal-qunit#6]
QUnit should fail if Steal encounters errors evaluating a module. Currently it only shows that 0 tests passed succesfully.

**Comment by matthewp** [comment]
Is there a way to do this? If steal-qunit successfully loads we could catch the error, is there a global QUnit.fail() or something that can be called?

But if steal-qunit fails to load we couldn't do this... but for the first case it's a good idea.

**Comment by matthewp** [comment]
I don't think this is possible. If steal fails to load that means QUnit fails to load, in which case it can't fail and show anything. Going to close.
